name: flutter_assessment_demo
description: A demo Flutter app for the assessment (mock auth, user list with caching, loopback WebRTC video).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.6
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  flutter_webrtc: ^0.9.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
